title: Institut für Übersetzen und Dolmetschen (IÜD), Universität Heidelberg
logo: /assets/img/logo.png
description: Professor Dr. Bogdan Babych, Institut für Übersetzen und Dolmetschen, Universität Heidelberg, Plöck 57a, 69117 Heidelberg, tel ‭+49 176 50280381, email bogdan.babych@iued.uni-heidelberg.de
show_downloads: false
theme: jekyll-theme-minimal
