title: Bogdan Babych, Universität Heidelberg
logo: /assets/img/logo.png
description: [Institute for Translation and Interpreting](http://iued.uni-heidelberg.de), [Heidelberg University](https://www.uni-heidelberg.de/en)
show_downloads: true
theme: jekyll-theme-minimal
