title: Bogdan Babych, Universität Heidelberg
logo: /assets/img/logo.png
description: Institute for Translation and Interpreting, Heidelberg University
show_downloads: true
theme: jekyll-theme-minimal
